/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectui;

import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.sql.Connection;
import java.util.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.time.LocalTime;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Harsh Kukreja
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents(); 
        pnlUpdateMenu.setVisible(false);
        pnlPrintData.setVisible(false);this.setIconImage(new ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\letter-v.png").getImage());
        updateTableData();
        initiateServer();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbData = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        pnlUpdateMenu = new javax.swing.JPanel();
        lblFoodName = new javax.swing.JLabel();
        txtFoodName = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        jcbCategory = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstItems = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        pnlPrintData = new javax.swing.JPanel();
        jcbUsers = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbUserData = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnPrintData = new javax.swing.JButton();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblDateValue = new javax.swing.JLabel();
        lblTimeValue = new javax.swing.JLabel();
        btnGetData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTablePanel.setBackground(new java.awt.Color(27, 20, 22));

        jtbData.setBackground(new java.awt.Color(27, 20, 22));
        jtbData.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        jtbData.setForeground(new java.awt.Color(243, 247, 248));
        jtbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbData);

        jPanel2.setBackground(new java.awt.Color(27, 20, 22));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 247, 248)));
        jPanel2.setForeground(new java.awt.Color(243, 247, 248));

        jButton1.setText("Update Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Order Done");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Print Bill");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Add Special");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Kalinga", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(243, 247, 248));
        jLabel7.setText("Admin");

        javax.swing.GroupLayout pnlTablePanelLayout = new javax.swing.GroupLayout(pnlTablePanel);
        pnlTablePanel.setLayout(pnlTablePanelLayout);
        pnlTablePanelLayout.setHorizontalGroup(
            pnlTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(pnlTablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlTablePanelLayout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTablePanelLayout.setVerticalGroup(
            pnlTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        getContentPane().add(pnlTablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlUpdateMenu.setBackground(new java.awt.Color(27, 20, 22));

        lblFoodName.setFont(new java.awt.Font("Kalinga", 0, 18)); // NOI18N
        lblFoodName.setForeground(new java.awt.Color(243, 247, 248));
        lblFoodName.setText("Food Name:");

        txtFoodName.setBackground(new java.awt.Color(27, 20, 22));
        txtFoodName.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        txtFoodName.setForeground(new java.awt.Color(243, 247, 248));

        lblPrice.setFont(new java.awt.Font("Kalinga", 0, 18)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(243, 247, 248));
        lblPrice.setText("Price           :");

        txtPrice.setBackground(new java.awt.Color(27, 20, 22));
        txtPrice.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(243, 247, 248));

        btnUpdate.setBackground(new java.awt.Color(27, 20, 22));
        btnUpdate.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(243, 247, 248));
        btnUpdate.setText("Update Now");
        btnUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 247, 248)));
        btnUpdate.setContentAreaFilled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jcbCategory.setBackground(new java.awt.Color(27, 20, 22));
        jcbCategory.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        jcbCategory.setForeground(new java.awt.Color(27, 20, 22));
        jcbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fastfood", "Meal ", "Beverage", "Desert", " ", " " }));

        lstItems.setBackground(new java.awt.Color(27, 20, 22));
        lstItems.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        lstItems.setForeground(new java.awt.Color(243, 247, 248));
        lstItems.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings =getDbMenu();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(lstItems);

        jLabel1.setFont(new java.awt.Font("Kalinga", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(243, 247, 248));
        jLabel1.setText("Update Menu");

        jLabel2.setFont(new java.awt.Font("Kalinga", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(243, 247, 248));
        jLabel2.setText("Current Menu");

        jLabel3.setFont(new java.awt.Font("Kalinga", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(243, 247, 248));
        jLabel3.setText("Enter the Item Data To be ");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setFont(new java.awt.Font("Kalinga", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(243, 247, 248));
        jLabel4.setText("Added Or Updated!");

        jButton7.setBackground(new java.awt.Color(27, 20, 22));
        jButton7.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(243, 247, 248));
        jButton7.setText("Add item");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 247, 248)));
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUpdateMenuLayout = new javax.swing.GroupLayout(pnlUpdateMenu);
        pnlUpdateMenu.setLayout(pnlUpdateMenuLayout);
        pnlUpdateMenuLayout.setHorizontalGroup(
            pnlUpdateMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdateMenuLayout.createSequentialGroup()
                .addGroup(pnlUpdateMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUpdateMenuLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(pnlUpdateMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)))
                    .addGroup(pnlUpdateMenuLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pnlUpdateMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFoodName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlUpdateMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFoodName, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUpdateMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlUpdateMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbCategory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlUpdateMenuLayout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlUpdateMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUpdateMenuLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel2))
                    .addGroup(pnlUpdateMenuLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUpdateMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(281, 281, 281))
        );
        pnlUpdateMenuLayout.setVerticalGroup(
            pnlUpdateMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdateMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUpdateMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUpdateMenuLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(76, 76, 76)
                        .addGroup(pnlUpdateMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFoodName)
                            .addComponent(txtFoodName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(pnlUpdateMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrice)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(jcbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(pnlUpdateMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate)
                            .addComponent(jButton7))
                        .addContainerGap())
                    .addGroup(pnlUpdateMenuLayout.createSequentialGroup()
                        .addGap(0, 58, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addComponent(jSeparator1)))
        );

        getContentPane().add(pnlUpdateMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 580));

        pnlPrintData.setBackground(new java.awt.Color(27, 20, 22));

        jcbUsers.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbUsersItemStateChanged(evt);
            }
        });
        jcbUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbUsersActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Kalinga", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(243, 247, 248));
        jLabel5.setText("User Id:");

        jtbUserData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtbUserData);

        jLabel6.setFont(new java.awt.Font("Kalinga", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(243, 247, 248));
        jLabel6.setText("Print Invoice");

        btnPrintData.setBackground(new java.awt.Color(27, 20, 22));
        btnPrintData.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        btnPrintData.setForeground(new java.awt.Color(243, 247, 248));
        btnPrintData.setText("Print");
        btnPrintData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 247, 248)));
        btnPrintData.setContentAreaFilled(false);
        btnPrintData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintDataActionPerformed(evt);
            }
        });

        lblDate.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(243, 247, 248));
        lblDate.setText("Date:");

        lblTime.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        lblTime.setForeground(new java.awt.Color(243, 247, 248));
        lblTime.setText("Time:");

        lblDateValue.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        lblDateValue.setForeground(new java.awt.Color(243, 247, 248));

        lblTimeValue.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        lblTimeValue.setForeground(new java.awt.Color(243, 247, 248));

        btnGetData.setText("Get Data");
        btnGetData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrintDataLayout = new javax.swing.GroupLayout(pnlPrintData);
        pnlPrintData.setLayout(pnlPrintDataLayout);
        pnlPrintDataLayout.setHorizontalGroup(
            pnlPrintDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrintDataLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlPrintDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrintDataLayout.createSequentialGroup()
                        .addComponent(lblDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDateValue))
                    .addGroup(pnlPrintDataLayout.createSequentialGroup()
                        .addComponent(lblTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTimeValue)))
                .addGap(150, 150, 150))
            .addGroup(pnlPrintDataLayout.createSequentialGroup()
                .addGroup(pnlPrintDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrintDataLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel6))
                    .addGroup(pnlPrintDataLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrintDataLayout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(btnPrintData, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrintDataLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnGetData)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPrintDataLayout.setVerticalGroup(
            pnlPrintDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrintDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addGroup(pnlPrintDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate)
                    .addComponent(lblDateValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPrintDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTime)
                    .addComponent(lblTimeValue))
                .addGap(5, 5, 5)
                .addGroup(pnlPrintDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGetData)
                .addGap(57, 57, 57)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(btnPrintData)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        getContentPane().add(pnlPrintData, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Event Handling
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pnlTablePanel.setVisible(false);
        pnlUpdateMenu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String buffer[]=getDbMenu();
        lstItems.setListData(buffer);
        insertIntoDb(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        insertIntoDb(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        pnlPrintData.setVisible(true);
        pnlTablePanel.setVisible(false);
        lblTimeValue.setText(""+time);
        getUsers();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jcbUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbUsersActionPerformed

    }//GEN-LAST:event_jcbUsersActionPerformed

    private void jcbUsersItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbUsersItemStateChanged
       //getUserOrder(jcbUsers.getSelectedItem().toString());
    }//GEN-LAST:event_jcbUsersItemStateChanged

    private void btnGetDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetDataActionPerformed
       
        getUserOrder(jcbUsers.getSelectedItem().toString());
    }//GEN-LAST:event_btnGetDataActionPerformed

    private void btnPrintDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintDataActionPerformed
        flag=true;
        MessageFormat header = new MessageFormat("Your Invoice");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}");
        try{
            jtbUserData.print(JTable.PrintMode.NORMAL,header,footer);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Some issue in printing : " + e.getMessage());
        }
    }//GEN-LAST:event_btnPrintDataActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selection=jtbData.getSelectedRow();
        jtbData.remove(selection);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton5ActionPerformed
    public static AdminPanel getAdminObj(){
        return adminRef;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               adminRef.setVisible(true);
            }
        });
    }
    /********************MY METHODS****************************************/
    /*
    By: Harsh Kukreja
    The below method gets all the data from the database of the ordered food items and updates it
    */
     private void updateTableData(){
        try {
            String sql="SELECT * FROM ordereditems ";
           preparedStatement = conn.prepareStatement(sql);
           rs = preparedStatement.executeQuery();
           jtbData.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Issue : "+e);
            
        }finally{
            try {
                rs.close();
                preparedStatement.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Problem in closing rs or preparedStatement : "+e);
            }
        }
    }
     /*
     By:Harsh Kukreja
     This method gets the menu from the database
     */
     public String[] getDbMenu(){
         String sql="SELECT * FROM canteendb";
         String[] s=new String[100];
         int i=0;
         try {
             preparedStatement=conn.prepareStatement(sql);
             rs=preparedStatement.executeQuery();
             if(rs.next()){
                while(rs.next()){
                    s[i]=new String(rs.getString("foodname"));
                    i++;
                    rs.next();
                }
                return s;
             }
             else{
                 JOptionPane.showMessageDialog(null,"Nothing in rs");
                 return null;
             }
         } catch (Exception e) {
             JOptionPane.showMessageDialog(null,"Some issue"+e);
             return null;
         }
     } 
     
     /*
     By: Harsh Kukreja
     This method inserts the food name , price, categoray of the food into the database  
     */
     public void insertIntoDb(boolean val){
         String sql;
         if(val){
             sql="INSERT INTO canteendb(foodname,price,foodcategory) VALUES (?,?,?)";
             try {
                preparedStatement=conn.prepareStatement(sql);
                preparedStatement.setString(1,txtFoodName.getText());
                preparedStatement.setString(2,txtPrice.getText());
                preparedStatement.setString(3,jcbCategory.getSelectedItem().toString());
               // preparedStatement.setString(4,lstItems.getSelectedValue());
                preparedStatement.execute();
            JOptionPane.showMessageDialog(null,"Item Inserted!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Issue in updating table"+ex);
        }
         }
         else{
             sql="UPDATE canteendb SET foodname=?,price=?,foodcategory=? WHERE foodname=?";
             try {
                preparedStatement=conn.prepareStatement(sql);
                preparedStatement.setString(1,txtFoodName.getText());
                preparedStatement.setString(2,txtPrice.getText());
                preparedStatement.setString(3,jcbCategory.getSelectedItem().toString());
                preparedStatement.setString(4,lstItems.getSelectedValue());
                preparedStatement.execute();
                JOptionPane.showMessageDialog(null,"Updated the item!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Issue in updating table"+ex);
        }
         }
        
     }
     
     /*
     By: Harsh Kukreja
     This method gets all the food in the menu and displays 
     */
     public void getMenuItems(){
        try {
            String sql="SELECT foodname FROM canteendb";
            preparedStatement=conn.prepareStatement(sql);
            preparedStatement.execute();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Issue in menu:"+ex);
        }       
     }
     
     /*
     By: Harsh Kukreja
     This method gets all the users which ordered the food 
     */
     public String[] getUsers(){
         String sql="SELECT email FROM users";
         String[] users=new String[100];
         try {
             preparedStatement=conn.prepareStatement(sql);
             rs=preparedStatement.executeQuery();
             while(rs.next()){
                 jcbUsers.addItem(rs.getString("email"));
             }
             return users;
         } catch (Exception e) {
             JOptionPane.showMessageDialog(null,"Issue from getUsers():"+e);
             return null;
         }
     }
     /*
     By: Harsh Kukreja
     This method gets all the food item ordered by the user
     */
     public void getUserOrder(String userName){
         String sql="SELECT name,quantity,totalprice FROM ordereditems WHERE email=? AND date=CURDATE()";
         try {
             preparedStatement=conn.prepareStatement(sql);
             System.out.println("PS bana");
             preparedStatement.setString(1,userName);
             System.out.println("Email pass kiya");
             rs=preparedStatement.executeQuery();
             jtbUserData.setModel(DbUtils.resultSetToTableModel(rs));
             System.out.println("rs bana");
             if(rs==null){
                 JOptionPane.showMessageDialog(null,"Rs null!");
             }
             else{
                System.out.println("Else me aaya");
                while(rs.next()){
                    System.out.println(rs.getString("name"));
                 }
             }
         } catch (Exception e) {
             System.out.println("Catch me aaya");
             JOptionPane.showMessageDialog(null, "Issue from user data:"+e);
         }
     }
     /*
     By: Harsh Kukreja
     This method initiattes the server using serversocket
     */
       public void initiateServer(){
           System.out.println("Inside inititate server");
         try{
                System.out.println("Inside try");
                ServerSocket socket=new ServerSocket(8765);
                System.out.println("Socket bana");
                Socket client = socket.accept();
                System.out.println("Accept hua");
                PrintWriter os = new PrintWriter(client.getOutputStream());
                System.out.println("Os bana");
              // os.println("You are connected to the server");
                JOptionPane.showMessageDialog(null,"Server Started");
                
         }
         catch(Exception e){
             JOptionPane.showMessageDialog(null,"Issue in initiating Server:"+e.getMessage());
             
         }
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetData;
    private javax.swing.JButton btnPrintData;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> jcbCategory;
    private javax.swing.JComboBox<String> jcbUsers;
    private javax.swing.JTable jtbData;
    private javax.swing.JTable jtbUserData;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDateValue;
    private javax.swing.JLabel lblFoodName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTimeValue;
    private javax.swing.JList<String> lstItems;
    private javax.swing.JPanel pnlPrintData;
    private javax.swing.JPanel pnlTablePanel;
    private javax.swing.JPanel pnlUpdateMenu;
    private javax.swing.JTextField txtFoodName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
ResultSet rs=null;
PreparedStatement preparedStatement;
Connection conn=MySqlConnect.connectDB();
LocalTime time=LocalTime.now();
Date date=new Date();
boolean flag=false;
static AdminPanel adminRef = new AdminPanel();
}
