/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectui;

import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;

/**
 *
 * @author Harsh Kukreja
 */
public class FeedbackForm extends javax.swing.JFrame {

    /**
     * Creates new form FeedbackForm
     */
    public FeedbackForm() {
        initComponents();
        rbtnTemp.setVisible(false);
        setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\letter-v.png").getImage());
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngEmojis = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        txtEmailFeedback = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblReview = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaReview = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        lblStars = new javax.swing.JLabel();
        jcb1 = new javax.swing.JCheckBox();
        jcb2 = new javax.swing.JCheckBox();
        jcb3 = new javax.swing.JCheckBox();
        jcb4 = new javax.swing.JCheckBox();
        jcb5 = new javax.swing.JCheckBox();
        lblExperience = new javax.swing.JLabel();
        rbtnSad = new javax.swing.JRadioButton();
        rbtnConfused = new javax.swing.JRadioButton();
        rbtnOk = new javax.swing.JRadioButton();
        rbtnHappy = new javax.swing.JRadioButton();
        rbtnLoved = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        lblNotification = new javax.swing.JLabel();
        rbtnTemp = new javax.swing.JRadioButton();
        btnBack = new javax.swing.JButton();
        lblEmailError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(720, 576));

        jPanel1.setBackground(new java.awt.Color(27, 20, 22));

        lblEmail.setBackground(new java.awt.Color(27, 20, 22));
        lblEmail.setFont(new java.awt.Font("Kalinga", 1, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(243, 247, 248));
        lblEmail.setText("Email:");

        txtEmailFeedback.setBackground(new java.awt.Color(27, 20, 22));
        txtEmailFeedback.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        txtEmailFeedback.setForeground(new java.awt.Color(243, 247, 248));
        txtEmailFeedback.setBorder(null);
        txtEmailFeedback.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFeedbackFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFeedbackFocusLost(evt);
            }
        });
        txtEmailFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailFeedbackActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(243, 247, 248));

        lblReview.setFont(new java.awt.Font("Kalinga", 1, 18)); // NOI18N
        lblReview.setForeground(new java.awt.Color(243, 247, 248));
        lblReview.setText("Your Review:");

        txtaReview.setBackground(new java.awt.Color(27, 20, 22));
        txtaReview.setColumns(20);
        txtaReview.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        txtaReview.setForeground(new java.awt.Color(243, 247, 248));
        txtaReview.setRows(5);
        txtaReview.setBorder(null);
        jScrollPane1.setViewportView(txtaReview);

        jSeparator2.setBackground(new java.awt.Color(243, 247, 248));

        lblStars.setBackground(new java.awt.Color(27, 20, 22));
        lblStars.setFont(new java.awt.Font("Kalinga", 1, 18)); // NOI18N
        lblStars.setForeground(new java.awt.Color(243, 247, 248));
        lblStars.setText("How Many Stars you will give us?");

        jcb1.setBackground(new java.awt.Color(27, 20, 22));
        jcb1.setBorder(null);
        jcb1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\star (1).png")); // NOI18N
        jcb1.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\star (2).png")); // NOI18N
        jcb1.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\star.png")); // NOI18N
        jcb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb1ActionPerformed(evt);
            }
        });

        jcb2.setBackground(new java.awt.Color(27, 20, 22));
        jcb2.setBorder(null);
        jcb2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\star (1).png")); // NOI18N
        jcb2.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\star (2).png")); // NOI18N
        jcb2.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\star.png")); // NOI18N
        jcb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb2ActionPerformed(evt);
            }
        });

        jcb3.setBackground(new java.awt.Color(27, 20, 22));
        jcb3.setBorder(null);
        jcb3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\star (1).png")); // NOI18N
        jcb3.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\star (2).png")); // NOI18N
        jcb3.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\star.png")); // NOI18N
        jcb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb3ActionPerformed(evt);
            }
        });

        jcb4.setBackground(new java.awt.Color(27, 20, 22));
        jcb4.setBorder(null);
        jcb4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\star (1).png")); // NOI18N
        jcb4.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\star (2).png")); // NOI18N
        jcb4.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\star.png")); // NOI18N
        jcb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb4ActionPerformed(evt);
            }
        });

        jcb5.setBackground(new java.awt.Color(27, 20, 22));
        jcb5.setBorder(null);
        jcb5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\star (1).png")); // NOI18N
        jcb5.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\star (2).png")); // NOI18N
        jcb5.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\star.png")); // NOI18N
        jcb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb5ActionPerformed(evt);
            }
        });

        lblExperience.setFont(new java.awt.Font("Kalinga", 1, 18)); // NOI18N
        lblExperience.setForeground(new java.awt.Color(243, 247, 248));
        lblExperience.setText("How was your experience?");

        rbtnSad.setBackground(new java.awt.Color(27, 20, 22));
        btngEmojis.add(rbtnSad);
        rbtnSad.setBorder(null);
        rbtnSad.setContentAreaFilled(false);
        rbtnSad.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\sad (8).png")); // NOI18N
        rbtnSad.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\sad (5).png")); // NOI18N
        rbtnSad.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\sad (10).png")); // NOI18N

        rbtnConfused.setBackground(new java.awt.Color(27, 20, 22));
        btngEmojis.add(rbtnConfused);
        rbtnConfused.setBorder(null);
        rbtnConfused.setContentAreaFilled(false);
        rbtnConfused.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\confused (3).png")); // NOI18N
        rbtnConfused.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\confused (2).png")); // NOI18N
        rbtnConfused.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\confused (1).png")); // NOI18N

        rbtnOk.setBackground(new java.awt.Color(27, 20, 22));
        btngEmojis.add(rbtnOk);
        rbtnOk.setBorder(null);
        rbtnOk.setContentAreaFilled(false);
        rbtnOk.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\smiling.png")); // NOI18N
        rbtnOk.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\smiling (1).png")); // NOI18N
        rbtnOk.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\smiling (2).png")); // NOI18N

        rbtnHappy.setBackground(new java.awt.Color(27, 20, 22));
        btngEmojis.add(rbtnHappy);
        rbtnHappy.setBorder(null);
        rbtnHappy.setContentAreaFilled(false);
        rbtnHappy.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\happy.png")); // NOI18N
        rbtnHappy.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\happy (1).png")); // NOI18N
        rbtnHappy.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\happy (2).png")); // NOI18N
        rbtnHappy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnHappyActionPerformed(evt);
            }
        });

        rbtnLoved.setBackground(new java.awt.Color(27, 20, 22));
        btngEmojis.add(rbtnLoved);
        rbtnLoved.setBorder(null);
        rbtnLoved.setContentAreaFilled(false);
        rbtnLoved.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\in-love.png")); // NOI18N
        rbtnLoved.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\in-love (1).png")); // NOI18N
        rbtnLoved.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\in-love (2).png")); // NOI18N

        jButton1.setBackground(new java.awt.Color(27, 20, 22));
        jButton1.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(243, 247, 248));
        jButton1.setText("Submit");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 247, 248)));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblNotification.setBackground(new java.awt.Color(27, 20, 22));
        lblNotification.setFont(new java.awt.Font("Kalinga", 0, 18)); // NOI18N
        lblNotification.setForeground(new java.awt.Color(51, 204, 0));

        btngEmojis.add(rbtnTemp);
        rbtnTemp.setSelected(true);
        rbtnTemp.setEnabled(false);
        rbtnTemp.setOpaque(false);

        btnBack.setBackground(new java.awt.Color(27, 20, 22));
        btnBack.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\left-arrow (6).png")); // NOI18N
        btnBack.setBorder(null);
        btnBack.setContentAreaFilled(false);
        btnBack.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\left-arrow (7).png")); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblEmailError.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblNotification)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcb1)
                                .addGap(18, 18, 18)
                                .addComponent(jcb2)
                                .addGap(18, 18, 18)
                                .addComponent(jcb3)
                                .addGap(18, 18, 18)
                                .addComponent(jcb4)
                                .addGap(18, 18, 18)
                                .addComponent(jcb5))
                            .addComponent(lblStars)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblReview)
                                    .addComponent(lblEmail)
                                    .addComponent(txtEmailFeedback)
                                    .addComponent(jSeparator1)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                                    .addComponent(jSeparator2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEmailError))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtnSad)
                                .addGap(30, 30, 30)
                                .addComponent(rbtnConfused)
                                .addGap(30, 30, 30)
                                .addComponent(rbtnOk)
                                .addGap(30, 30, 30)
                                .addComponent(rbtnHappy)
                                .addGap(30, 30, 30)
                                .addComponent(rbtnLoved)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnTemp))
                            .addComponent(lblExperience)))
                    .addComponent(btnBack))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnBack)
                .addGap(38, 38, 38)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmailFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblReview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblStars)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb1)
                    .addComponent(jcb2)
                    .addComponent(jcb3)
                    .addComponent(jcb4)
                    .addComponent(jcb5))
                .addGap(18, 18, 18)
                .addComponent(lblExperience)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnSad)
                            .addComponent(rbtnConfused)
                            .addComponent(rbtnOk)
                            .addComponent(rbtnHappy)
                            .addComponent(rbtnLoved))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtnTemp)
                        .addGap(43, 43, 43)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(lblNotification))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Event Handling
    private void jcb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb1ActionPerformed
        // TODO add your handling code here:
        jcb1.setSelected(true);
        jcb2.setSelected(false);
        jcb3.setSelected(false);
        jcb4.setSelected(false);
        jcb5.setSelected(false); 
    }//GEN-LAST:event_jcb1ActionPerformed

    private void jcb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb2ActionPerformed
        // TODO add your handling code here:
        jcb1.setSelected(true);
        jcb2.setSelected(true);
        jcb3.setSelected(false);
        jcb4.setSelected(false);
        jcb5.setSelected(false); 
    }//GEN-LAST:event_jcb2ActionPerformed

    private void jcb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb3ActionPerformed
        // TODO add your handling code here:
        jcb1.setSelected(true);
        jcb2.setSelected(true);
        jcb3.setSelected(true);
        jcb4.setSelected(false);
        jcb5.setSelected(false); 
    }//GEN-LAST:event_jcb3ActionPerformed

    private void jcb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb4ActionPerformed
        // TODO add your handling code here:
        jcb1.setSelected(true);
        jcb2.setSelected(true);
        jcb3.setSelected(true);
        jcb4.setSelected(true);
        jcb5.setSelected(false);
    }//GEN-LAST:event_jcb4ActionPerformed

    private void jcb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb5ActionPerformed
        // TODO add your handling code here:
        jcb1.setSelected(true);
        jcb2.setSelected(true);
        jcb3.setSelected(true);
        jcb4.setSelected(true);
        jcb5.setSelected(true); 
    }//GEN-LAST:event_jcb5ActionPerformed

    private void rbtnHappyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnHappyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnHappyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!txtEmailFeedback.getText().equals("") &&!txtaReview.getText().equals("")){
            
           if(validateEmail()){
            lblNotification.setForeground(Color.green);   
            new Mail().mail(txtEmailFeedback.getText(),txtaReview.getText());
            lblNotification.setText("Thank you!We will look forward to you suggestions :)");
            lblEmailError.setText("");
            clearFields();
           }
        }
        else if(txtEmailFeedback.getText().equals("") &&txtaReview.getText().equals("")){
            lblEmailError.setForeground(Color.red);
            lblEmailError.setText("Some Fields Are Empty");
            txtEmailFeedback.setForeground(f3f7f8);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtEmailFeedbackFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFeedbackFocusGained
        // TODO add your handling code here:
        lblNotification.setForeground(f3f7f8);
        lblNotification.setText("Email Should be in the form:'someone@address.com'");
    }//GEN-LAST:event_txtEmailFeedbackFocusGained

    private void txtEmailFeedbackFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFeedbackFocusLost
        // TODO add your handling code here:
        lblNotification.setText("");
    }//GEN-LAST:event_txtEmailFeedbackFocusLost

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        StartingPage obj = StartingPage.getObject();
        obj.setVisible(true);
        //obj.getMainPanel(false).setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtEmailFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailFeedbackActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtEmailFeedbackActionPerformed

      public void clearFields(){
        jcb1.setSelected(false);
        jcb2.setSelected(false);
        jcb3.setSelected(false);
        jcb4.setSelected(false);
        jcb5.setSelected(false);
        rbtnSad.setSelected(false);
        rbtnConfused.setSelected(false);
        rbtnOk.setSelected(false);
        rbtnHappy.setSelected(false);
        rbtnLoved.setSelected(false);
        rbtnTemp.setSelected(true);
        txtEmailFeedback.setText("");
        txtaReview.setText("");
      }
      /*
      By: Harsh Kukreja
      This below method validates the email address of the user wheather it satisfies conditions of the emails
      */
       private boolean validateEmail(){
            String emailPatternString = "^[_A-Za-z0-9\\+]+(\\.[_A-Za-z0-9-\\+]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
            Pattern emailPattern = Pattern.compile(emailPatternString);
            Matcher emailMatcher = emailPattern.matcher(txtEmailFeedback.getText());
            if(emailMatcher.matches()){
                return true;
            }
            else{
                lblNotification.setForeground(Color.red);
                txtEmailFeedback.setForeground(Color.red);
                lblNotification.setText("Please enter correct email");
                
               return false;
            }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Macintosh*".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeedbackForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeedbackForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeedbackForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeedbackForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FeedbackForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.ButtonGroup btngEmojis;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JCheckBox jcb1;
    private javax.swing.JCheckBox jcb2;
    private javax.swing.JCheckBox jcb3;
    private javax.swing.JCheckBox jcb4;
    private javax.swing.JCheckBox jcb5;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailError;
    private javax.swing.JLabel lblExperience;
    private javax.swing.JLabel lblNotification;
    private javax.swing.JLabel lblReview;
    private javax.swing.JLabel lblStars;
    private javax.swing.JRadioButton rbtnConfused;
    private javax.swing.JRadioButton rbtnHappy;
    private javax.swing.JRadioButton rbtnLoved;
    private javax.swing.JRadioButton rbtnOk;
    private javax.swing.JRadioButton rbtnSad;
    private javax.swing.JRadioButton rbtnTemp;
    private javax.swing.JTextField txtEmailFeedback;
    private javax.swing.JTextArea txtaReview;
    // End of variables declaration//GEN-END:variables
    Color f3f7f8 = new Color(243,247,248);
}
