/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectui;

import java.awt.image.BufferedImage;
import java.io.File;
import javax.swing.ImageIcon;
import net.coobird.thumbnailator.Thumbnails;
import static projectui.LocationFrame.flag;

/**
 *
 * @author Harsh Kukreja
 */
public class ImagesPanel extends javax.swing.JFrame {

    /**
     * Creates new form ImagesPanel
     * This method takes the path images in the array and displays in the frame
     */
    public ImagesPanel() {
        initComponents();
       try {
            File imagePath = new File(images[0]);
        BufferedImage thumbnail = Thumbnails.of(imagePath).size(720,576).asBufferedImage();
        lblImage.setIcon(new ImageIcon(thumbnail));
        } catch (Exception e) {}
       
            btnLeft.setEnabled(false);
        this.setLocationRelativeTo(null);
    }
    
         String[] images = {
        "C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\Food Items\\VadaPav.png" ,
        "C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\Food Items\\PavBhaji.png",
        "C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\Food Items\\Idli.png",
        "C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\Food Items\\Vada.png",
        "C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\Food Items\\Noodles.png",
        "C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\Food Items\\Biryani.png",
        "C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\Food Items\\Misal.png",
        "C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\Food Items\\Samosa.png",
        "C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\Food Items\\Icecream.png",
        "C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\Food Items\\GulabJamun.png",
        "C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\Food Items\\Dosa.png"};
    
    /*
         By: Harsh Kukreja
         This method uses Thumbnailator jar file and covert every image into a fixed size then changes the image
    */
    public void moveIcon(){
        try {
            File imagePath = new File(images[i]);
        BufferedImage thumbnail = Thumbnails.of(imagePath).size(720,576).asBufferedImage();
        lblImage.setIcon(new ImageIcon(thumbnail));
        } catch (Exception e) {}
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLeft = new javax.swing.JButton();
        btnRight = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLeft.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\Food Items\\left-arrow.png")); // NOI18N
        btnLeft.setBorder(null);
        btnLeft.setBorderPainted(false);
        btnLeft.setContentAreaFilled(false);
        btnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeftActionPerformed(evt);
            }
        });
        jPanel1.add(btnLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        btnRight.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\Food Items\\right-arrow.png")); // NOI18N
        btnRight.setBorder(null);
        btnRight.setBorderPainted(false);
        btnRight.setContentAreaFilled(false);
        btnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRightActionPerformed(evt);
            }
        });
        jPanel1.add(btnRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, -1, -1));

        btnBack.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\left-arrow (6).png")); // NOI18N
        btnBack.setBorder(null);
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\left-arrow (7).png")); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblImage.setPreferredSize(new java.awt.Dimension(720, 576));
        jPanel1.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Event handling
    private void btnLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeftActionPerformed
        // TODO add your handling code here:
        if(i>=0){
            i--;
            moveIcon();
            if(i==0){
                btnLeft.setEnabled(false);
            }
            btnRight.setEnabled(true);
        }else {
            i=0;
            moveIcon();
            btnLeft.setEnabled(false);
        } 
    }//GEN-LAST:event_btnLeftActionPerformed

    private void btnRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRightActionPerformed
        // TODO add your handling code here:
        if (i<=10) {
            i++;
            moveIcon();
            if(i==10){
                btnRight.setEnabled(false);
            }
            btnLeft.setEnabled(true);
        } else {
            i=9;
            moveIcon();
            btnRight.setEnabled(false);     
        }
    }//GEN-LAST:event_btnRightActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        StartingPage obj = StartingPage.getObject();
        obj.setVisible(true);
        dispose();
        flag=false;
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImagesPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImagesPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImagesPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImagesPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImagesPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLeft;
    private javax.swing.JButton btnRight;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImage;
    // End of variables declaration//GEN-END:variables
    int i =0;
}
