/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectui;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Rohit Methwani
 */
public class StartingPage extends javax.swing.JFrame {

    /**
     * Creates new form StartingPage
     */
    public StartingPage() {
        initComponents();
        connection=MySqlConnect.connectDB();
        pnlSignUpAndLogin.setVisible(false);
        pnlSignUpData.setVisible(false);
        pnlLoginPanel.setVisible(false);
        btnLocation.setContentAreaFilled(false);
        pnlMainPanel.setVisible(false);
        pnlMainPanel1.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\letter-v.png").getImage());
        page=0;
       
        
    //t.start();
        pack();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlMainPanel = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        btnImages = new javax.swing.JButton();
        btnSuggestions = new javax.swing.JButton();
        btnOrderNow = new javax.swing.JButton();
        btnLocation = new javax.swing.JButton();
        pnlSignUpAndLogin = new javax.swing.JPanel();
        pnlRightSidePanel = new javax.swing.JPanel();
        pnlToolbarsignUpAndLogin = new javax.swing.JPanel();
        btnBackButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pnlSignUpData = new javax.swing.JPanel();
        lblsignUp = new javax.swing.JLabel();
        btnGo = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jspEmail = new javax.swing.JSeparator();
        jspConfirmEmail = new javax.swing.JSeparator();
        jspPassword = new javax.swing.JSeparator();
        jspConfirmPassword = new javax.swing.JSeparator();
        btnAlreadyUser = new javax.swing.JButton();
        lblNotification = new javax.swing.JLabel();
        jcbTermsAndConditions = new javax.swing.JCheckBox();
        lblEmail = new javax.swing.JLabel();
        lblConfirmEmail = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblConfirmPassword = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtConfirmPassword = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        txtConfirmEmail = new javax.swing.JTextField();
        pnlLoginPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        lblEmailLogin = new javax.swing.JLabel();
        lblPasswordLogin = new javax.swing.JLabel();
        btnGoLogin = new javax.swing.JButton();
        btnCanelLogin = new javax.swing.JButton();
        txtEmailLogin = new javax.swing.JTextField();
        txtPasswordLogin = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        lblNotificationLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlMainPanel1 = new javax.swing.JPanel();
        lblVesLogo = new javax.swing.JLabel();
        lblVivekanand = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        lblVcm = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        btnFeedback = new javax.swing.JButton();
        btnWhatWeServe = new javax.swing.JButton();
        btnOurCoordinates = new javax.swing.JButton();
        lblVcmLogo = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        lblFeedback = new javax.swing.JLabel();
        lblImages = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        lblVesBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(720, 576));

        pnlMainPanel.setBackground(new java.awt.Color(27, 20, 22));
        pnlMainPanel.setMinimumSize(new java.awt.Dimension(720, 576));
        pnlMainPanel.setPreferredSize(new java.awt.Dimension(720, 576));
        pnlMainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlMainPanel.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 39, -1, -1));

        btnImages.setBackground(new java.awt.Color(27, 20, 22));
        btnImages.setToolTipText("What we serve");
        btnImages.setBorder(null);
        btnImages.setContentAreaFilled(false);
        btnImages.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagesActionPerformed(evt);
            }
        });
        pnlMainPanel.add(btnImages, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 287, -1, -1));

        btnSuggestions.setBackground(new java.awt.Color(27, 20, 22));
        btnSuggestions.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/C:/Users/Raju Methwani/Downloads/bulb (3).png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btnSuggestions.setToolTipText("If you can help us to improve");
        btnSuggestions.setBorder(null);
        btnSuggestions.setContentAreaFilled(false);
        btnSuggestions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSuggestions.setRolloverIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/C:/Users/Raju Methwani/Downloads/bulb (4).png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        btnSuggestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuggestionsActionPerformed(evt);
            }
        });
        pnlMainPanel.add(btnSuggestions, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 287, -1, -1));

        btnOrderNow.setBackground(new java.awt.Color(27, 20, 22));
        btnOrderNow.setToolTipText("Order Now");
        btnOrderNow.setBorder(null);
        btnOrderNow.setContentAreaFilled(false);
        btnOrderNow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOrderNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderNowActionPerformed(evt);
            }
        });
        pnlMainPanel.add(btnOrderNow, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 287, -1, -1));

        btnLocation.setBackground(new java.awt.Color(27, 20, 22));
        btnLocation.setBorder(null);
        btnLocation.setBorderPainted(false);
        btnLocation.setContentAreaFilled(false);
        btnLocation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocationActionPerformed(evt);
            }
        });
        pnlMainPanel.add(btnLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 287, -1, -1));

        pnlSignUpAndLogin.setBackground(new java.awt.Color(27, 20, 22));
        pnlSignUpAndLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlRightSidePanel.setBackground(new java.awt.Color(27, 20, 22));
        pnlRightSidePanel.setLayout(null);

        pnlToolbarsignUpAndLogin.setBackground(new java.awt.Color(27, 20, 22));

        btnBackButton.setBackground(new java.awt.Color(27, 20, 22));
        btnBackButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\left-arrow (6).png")); // NOI18N
        btnBackButton.setBorder(null);
        btnBackButton.setContentAreaFilled(false);
        btnBackButton.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\left-arrow (7).png")); // NOI18N
        btnBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(27, 20, 22));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\error (6).png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\error (7).png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlToolbarsignUpAndLoginLayout = new javax.swing.GroupLayout(pnlToolbarsignUpAndLogin);
        pnlToolbarsignUpAndLogin.setLayout(pnlToolbarsignUpAndLoginLayout);
        pnlToolbarsignUpAndLoginLayout.setHorizontalGroup(
            pnlToolbarsignUpAndLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToolbarsignUpAndLoginLayout.createSequentialGroup()
                .addComponent(btnBackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );
        pnlToolbarsignUpAndLoginLayout.setVerticalGroup(
            pnlToolbarsignUpAndLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToolbarsignUpAndLoginLayout.createSequentialGroup()
                .addGroup(pnlToolbarsignUpAndLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBackButton)
                    .addComponent(jButton1))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlRightSidePanel.add(pnlToolbarsignUpAndLogin);
        pnlToolbarsignUpAndLogin.setBounds(0, 0, 360, 30);

        pnlSignUpData.setBackground(new java.awt.Color(27, 20, 22));
        pnlSignUpData.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(243, 247, 248), 1, true));
        pnlSignUpData.setForeground(new java.awt.Color(243, 247, 248));

        lblsignUp.setBackground(new java.awt.Color(27, 20, 22));
        lblsignUp.setFont(new java.awt.Font("Kalinga", 0, 24)); // NOI18N
        lblsignUp.setForeground(new java.awt.Color(243, 247, 248));
        lblsignUp.setText("Sign Up");

        btnGo.setBackground(new java.awt.Color(27, 20, 22));
        btnGo.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        btnGo.setForeground(new java.awt.Color(243, 247, 248));
        btnGo.setText("Go!");
        btnGo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 247, 248)));
        btnGo.setContentAreaFilled(false);
        btnGo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(27, 20, 22));
        btnCancel.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(243, 247, 248));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 247, 248)));
        btnCancel.setContentAreaFilled(false);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jspEmail.setForeground(new java.awt.Color(243, 247, 248));

        jspConfirmEmail.setForeground(new java.awt.Color(243, 247, 248));

        jspPassword.setForeground(new java.awt.Color(243, 247, 248));

        jspConfirmPassword.setForeground(new java.awt.Color(243, 247, 248));

        btnAlreadyUser.setBackground(new java.awt.Color(27, 20, 22));
        btnAlreadyUser.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        btnAlreadyUser.setForeground(new java.awt.Color(243, 247, 248));
        btnAlreadyUser.setText("Already a user?Login Now");
        btnAlreadyUser.setBorder(null);
        btnAlreadyUser.setContentAreaFilled(false);
        btnAlreadyUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlreadyUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnAlreadyUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnAlreadyUserFocusLost(evt);
            }
        });
        btnAlreadyUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlreadyUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlreadyUserMouseExited(evt);
            }
        });
        btnAlreadyUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlreadyUserActionPerformed(evt);
            }
        });

        lblNotification.setBackground(new java.awt.Color(27, 20, 22));
        lblNotification.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        lblNotification.setForeground(new java.awt.Color(243, 247, 248));
        lblNotification.setText("Notification");

        jcbTermsAndConditions.setBackground(new java.awt.Color(27, 20, 22));
        jcbTermsAndConditions.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        jcbTermsAndConditions.setForeground(new java.awt.Color(243, 247, 248));
        jcbTermsAndConditions.setText("I agree all Terms And Conditions.");
        jcbTermsAndConditions.setBorder(null);
        jcbTermsAndConditions.setBorderPainted(true);
        jcbTermsAndConditions.setContentAreaFilled(false);
        jcbTermsAndConditions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbTermsAndConditions.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\check-box-empty.png")); // NOI18N
        jcbTermsAndConditions.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\black-check-box-with-white-check (1).png")); // NOI18N

        lblEmail.setBackground(new java.awt.Color(27, 20, 22));
        lblEmail.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(243, 247, 248));
        lblEmail.setText("Email");
        lblEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmailMouseClicked(evt);
            }
        });

        lblConfirmEmail.setBackground(new java.awt.Color(27, 20, 22));
        lblConfirmEmail.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        lblConfirmEmail.setForeground(new java.awt.Color(243, 247, 248));
        lblConfirmEmail.setText("Confirm Email");
        lblConfirmEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConfirmEmailMouseClicked(evt);
            }
        });

        lblPassword.setBackground(new java.awt.Color(27, 20, 22));
        lblPassword.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(243, 247, 248));
        lblPassword.setText("Password");
        lblPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPasswordMouseClicked(evt);
            }
        });

        lblConfirmPassword.setBackground(new java.awt.Color(27, 20, 22));
        lblConfirmPassword.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        lblConfirmPassword.setForeground(new java.awt.Color(243, 247, 248));
        lblConfirmPassword.setText("Confirm Password");
        lblConfirmPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConfirmPasswordMouseClicked(evt);
            }
        });

        txtEmail.setBackground(new java.awt.Color(27, 20, 22));
        txtEmail.setFont(new java.awt.Font("Kalinga", 0, 11)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(243, 247, 248));
        txtEmail.setBorder(null);
        txtEmail.setCaretColor(new java.awt.Color(243, 247, 248));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });

        txtConfirmPassword.setBackground(new java.awt.Color(27, 20, 22));
        txtConfirmPassword.setForeground(new java.awt.Color(243, 247, 248));
        txtConfirmPassword.setBorder(null);
        txtConfirmPassword.setCaretColor(new java.awt.Color(243, 247, 248));
        txtConfirmPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConfirmPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConfirmPasswordFocusLost(evt);
            }
        });

        txtPassword.setBackground(new java.awt.Color(27, 20, 22));
        txtPassword.setForeground(new java.awt.Color(243, 247, 248));
        txtPassword.setBorder(null);
        txtPassword.setCaretColor(new java.awt.Color(243, 247, 248));
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });

        txtConfirmEmail.setBackground(new java.awt.Color(27, 20, 22));
        txtConfirmEmail.setFont(new java.awt.Font("Kalinga", 0, 11)); // NOI18N
        txtConfirmEmail.setForeground(new java.awt.Color(243, 247, 248));
        txtConfirmEmail.setBorder(null);
        txtConfirmEmail.setCaretColor(new java.awt.Color(243, 247, 248));
        txtConfirmEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConfirmEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConfirmEmailFocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnlSignUpDataLayout = new javax.swing.GroupLayout(pnlSignUpData);
        pnlSignUpData.setLayout(pnlSignUpDataLayout);
        pnlSignUpDataLayout.setHorizontalGroup(
            pnlSignUpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSignUpDataLayout.createSequentialGroup()
                .addGroup(pnlSignUpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSignUpDataLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSignUpDataLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(lblsignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlSignUpDataLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlSignUpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSignUpDataLayout.createSequentialGroup()
                        .addGroup(pnlSignUpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcbTermsAndConditions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAlreadyUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25))
                    .addGroup(pnlSignUpDataLayout.createSequentialGroup()
                        .addComponent(lblNotification)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSignUpDataLayout.createSequentialGroup()
                        .addGroup(pnlSignUpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlSignUpDataLayout.createSequentialGroup()
                                .addComponent(lblConfirmEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtConfirmEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlSignUpDataLayout.createSequentialGroup()
                                .addComponent(lblPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlSignUpDataLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblConfirmPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlSignUpDataLayout.createSequentialGroup()
                                .addComponent(lblEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jspEmail)
                            .addComponent(jspConfirmEmail)
                            .addComponent(jspPassword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jspConfirmPassword))
                        .addGap(31, 31, 31))))
        );
        pnlSignUpDataLayout.setVerticalGroup(
            pnlSignUpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSignUpDataLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblsignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(pnlSignUpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(pnlSignUpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConfirmEmail)
                    .addComponent(txtConfirmEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspConfirmEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(pnlSignUpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(pnlSignUpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConfirmPassword)
                    .addComponent(txtConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNotification)
                .addGap(18, 18, 18)
                .addComponent(jcbTermsAndConditions)
                .addGap(18, 18, 18)
                .addGroup(pnlSignUpDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGo)
                    .addComponent(btnCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAlreadyUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlRightSidePanel.add(pnlSignUpData);
        pnlSignUpData.setBounds(22, 39, 320, 520);

        pnlLoginPanel.setBackground(new java.awt.Color(27, 20, 22));

        jPanel1.setBackground(new java.awt.Color(27, 20, 22));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(243, 247, 248), 1, true));

        lblLogin.setBackground(new java.awt.Color(27, 20, 22));
        lblLogin.setFont(new java.awt.Font("Kalinga", 0, 24)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(243, 247, 248));
        lblLogin.setText("Login");

        lblEmailLogin.setBackground(new java.awt.Color(27, 20, 22));
        lblEmailLogin.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        lblEmailLogin.setForeground(new java.awt.Color(243, 247, 248));
        lblEmailLogin.setText("Email");

        lblPasswordLogin.setBackground(new java.awt.Color(27, 20, 22));
        lblPasswordLogin.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        lblPasswordLogin.setForeground(new java.awt.Color(243, 247, 248));
        lblPasswordLogin.setText("Password");

        btnGoLogin.setBackground(new java.awt.Color(27, 20, 22));
        btnGoLogin.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        btnGoLogin.setForeground(new java.awt.Color(243, 247, 248));
        btnGoLogin.setText("Go");
        btnGoLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 247, 248)));
        btnGoLogin.setContentAreaFilled(false);
        btnGoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoLoginActionPerformed(evt);
            }
        });

        btnCanelLogin.setBackground(new java.awt.Color(27, 20, 22));
        btnCanelLogin.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        btnCanelLogin.setForeground(new java.awt.Color(243, 247, 248));
        btnCanelLogin.setText("Cancel");
        btnCanelLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 247, 248)));
        btnCanelLogin.setContentAreaFilled(false);

        txtEmailLogin.setBackground(new java.awt.Color(27, 20, 22));
        txtEmailLogin.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        txtEmailLogin.setForeground(new java.awt.Color(243, 247, 248));
        txtEmailLogin.setBorder(null);
        txtEmailLogin.setOpaque(false);

        txtPasswordLogin.setBackground(new java.awt.Color(27, 20, 22));
        txtPasswordLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPasswordLogin.setForeground(new java.awt.Color(243, 247, 248));
        txtPasswordLogin.setBorder(null);
        txtPasswordLogin.setOpaque(false);
        txtPasswordLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordLoginActionPerformed(evt);
            }
        });

        lblNotificationLogin.setBackground(new java.awt.Color(27, 20, 22));
        lblNotificationLogin.setFont(new java.awt.Font("Kalinga", 0, 12)); // NOI18N
        lblNotificationLogin.setForeground(new java.awt.Color(243, 247, 248));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(21, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNotificationLogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblLogin)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPasswordLogin)
                                .addGap(18, 18, 18)
                                .addComponent(txtPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblEmailLogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEmailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lblLogin)
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailLogin)
                    .addComponent(txtEmailLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPasswordLogin))
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblNotificationLogin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGoLogin)
                            .addComponent(btnCanelLogin))))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlLoginPanelLayout = new javax.swing.GroupLayout(pnlLoginPanel);
        pnlLoginPanel.setLayout(pnlLoginPanelLayout);
        pnlLoginPanelLayout.setHorizontalGroup(
            pnlLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnlLoginPanelLayout.setVerticalGroup(
            pnlLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pnlRightSidePanel.add(pnlLoginPanel);
        pnlLoginPanel.setBounds(0, 0, 360, 576);

        pnlSignUpAndLogin.add(pnlRightSidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 360, 576));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\Login and signup images\\LoginAndSignup.png")); // NOI18N
        pnlSignUpAndLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlMainPanel1.setMinimumSize(new java.awt.Dimension(720, 576));
        pnlMainPanel1.setPreferredSize(new java.awt.Dimension(720, 576));
        pnlMainPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVesLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\Other Images\\ves-logo.png")); // NOI18N
        pnlMainPanel1.add(lblVesLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblVivekanand.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\Other Images\\vivekanand.png")); // NOI18N
        pnlMainPanel1.add(lblVivekanand, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, -1, -1));

        lblWelcome.setFont(new java.awt.Font("Kalinga", 1, 32)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(27, 20, 22));
        lblWelcome.setText("Welcome to VES Canteen!");
        pnlMainPanel1.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 420, -1));

        lblVcm.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        lblVcm.setForeground(new java.awt.Color(27, 20, 22));
        lblVcm.setText("VCM");
        pnlMainPanel1.add(lblVcm, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        btnMenu.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\chef (4).png")); // NOI18N
        btnMenu.setBorder(null);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\chef (3).png")); // NOI18N
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        pnlMainPanel1.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        btnFeedback.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\bulb (4).png")); // NOI18N
        btnFeedback.setBorder(null);
        btnFeedback.setContentAreaFilled(false);
        btnFeedback.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\bulb (3).png")); // NOI18N
        btnFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeedbackActionPerformed(evt);
            }
        });
        pnlMainPanel1.add(btnFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        btnWhatWeServe.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\photo-camera (2).png")); // NOI18N
        btnWhatWeServe.setBorder(null);
        btnWhatWeServe.setContentAreaFilled(false);
        btnWhatWeServe.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\photo-camera (1).png")); // NOI18N
        btnWhatWeServe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWhatWeServeActionPerformed(evt);
            }
        });
        pnlMainPanel1.add(btnWhatWeServe, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));

        btnOurCoordinates.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\map (4).png")); // NOI18N
        btnOurCoordinates.setBorder(null);
        btnOurCoordinates.setContentAreaFilled(false);
        btnOurCoordinates.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\map (2).png")); // NOI18N
        btnOurCoordinates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOurCoordinatesActionPerformed(evt);
            }
        });
        pnlMainPanel1.add(btnOurCoordinates, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, -1));

        lblVcmLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\dinner.png")); // NOI18N
        pnlMainPanel1.add(lblVcmLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        lblMenu.setFont(new java.awt.Font("Kalinga", 1, 18)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(27, 20, 22));
        lblMenu.setText("Our Menu");
        pnlMainPanel1.add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, -1));

        lblFeedback.setFont(new java.awt.Font("Kalinga", 1, 18)); // NOI18N
        lblFeedback.setForeground(new java.awt.Color(27, 20, 22));
        lblFeedback.setText("Feedback");
        pnlMainPanel1.add(lblFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, -1, -1));

        lblImages.setFont(new java.awt.Font("Kalinga", 1, 18)); // NOI18N
        lblImages.setForeground(new java.awt.Color(27, 20, 22));
        lblImages.setText("What We Serve");
        pnlMainPanel1.add(lblImages, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, -1, -1));

        lblLocation.setFont(new java.awt.Font("Kalinga", 1, 18)); // NOI18N
        lblLocation.setForeground(new java.awt.Color(27, 20, 22));
        lblLocation.setText("Our Co-ordinates");
        pnlMainPanel1.add(lblLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, -1, -1));

        lblVesBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\Other Images\\vesbackground.png")); // NOI18N
        pnlMainPanel1.add(lblVesBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlSignUpAndLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlMainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlSignUpAndLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlMainPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   //Event Handling
    private void btnImagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagesActionPerformed
        ImagesPanel obj = new ImagesPanel();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnImagesActionPerformed

    private void btnAlreadyUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlreadyUserActionPerformed
        pnlSignUpData.setVisible(false);
        pnlLoginPanel.setVisible(true);
        page=2;
    }//GEN-LAST:event_btnAlreadyUserActionPerformed

    private void btnOrderNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderNowActionPerformed
        pnlMainPanel.setVisible(false);
        pnlSignUpAndLogin.setVisible(true);
        pnlSignUpData.setVisible(true);
        page=1;
    }//GEN-LAST:event_btnOrderNowActionPerformed

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        String query="INSERT INTO users (email,password) VALUES (?,?)";
        System.out.println("Inside Go ");
        System.out.println(checkData());
        if(checkData() && checkCheckbox()){
            if(validateEmail() && checkPassword()){
                        try {
                            System.out.println(checkUser());
                            if(checkUser()){
                                statement=connection.prepareStatement(query);
                                statement.setString(1, txtEmail.getText());
                                statement.setString(2, txtPassword.getText());
                                boolean status=statement.execute();
                               if(!status){
                                   email=txtEmail.getText();
                                   lblNotification.setForeground(Color.green);
                                   lblNotification.setText("Welcome to the family!");
                                   if(initiateClient()){
                                       LoadingFrame obj = new LoadingFrame();
                                       obj.setVisible(true);
                                       dispose();
                                   }
                               }
                               else{
                                   lblNotification.setForeground(Color.red);
                                   lblNotification.setText("Some issue");
                               }
                          }
                            else{
                                lblNotification.setForeground(Color.red);
                                lblNotification.setText("User with this email already exists");
                            }
                        } catch (Exception e) {
                            lblNotification.setForeground(Color.red);
                            lblNotification.setText("Some Issue");
                            System.out.println(e);
                        }
             }
         
        }
        else{
            txtEmail.setForeground(Color.red);
            txtConfirmEmail.setForeground(Color.red);
            txtPassword.setForeground(Color.red);
            txtConfirmPassword.setForeground(Color.red);
            lblNotification.setForeground(Color.red);
            lblNotification.setText("Please fill all details");
         
        }
        
    }//GEN-LAST:event_btnGoActionPerformed

    private void btnLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocationActionPerformed
        LocationFrame obj = new LocationFrame();
        startingPage.dispose();
        obj.setVisible(true);
    }//GEN-LAST:event_btnLocationActionPerformed

    private void btnAlreadyUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnAlreadyUserFocusGained
        btnAlreadyUser.setForeground(new Color(220,57,58));
        btnAlreadyUser.setFont(new Font("Kalinga",Font.BOLD,14));
    }//GEN-LAST:event_btnAlreadyUserFocusGained

    private void btnAlreadyUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlreadyUserMouseEntered
        btnAlreadyUser.setForeground(new Color(220,57,58));
        btnAlreadyUser.setFont(new Font("Kalinga",Font.BOLD,14));
    }//GEN-LAST:event_btnAlreadyUserMouseEntered

    private void btnAlreadyUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnAlreadyUserFocusLost
        btnAlreadyUser.setForeground(f3f7f8);
        btnAlreadyUser.setFont(new Font("Kalinga",Font.PLAIN,14));
    }//GEN-LAST:event_btnAlreadyUserFocusLost

    private void btnAlreadyUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlreadyUserMouseExited
        btnAlreadyUser.setForeground(f3f7f8);
        btnAlreadyUser.setFont(new Font("Kalinga",Font.PLAIN,14));
    }//GEN-LAST:event_btnAlreadyUserMouseExited

    private void btnGoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoLoginActionPerformed
       String query="SELECT * FROM users WHERE email=? AND password=?";
        try {
            System.out.println("Inside go");
                statement=connection.prepareStatement(query);
                statement.setString(1,txtEmailLogin.getText());
                statement.setString(2,txtPasswordLogin.getText());
                rs=statement.executeQuery();
                while(rs.next()){
                    System.out.println("Inside while");
                    if(rs.getString("email").equals(txtEmailLogin.getText())){
                        if(rs.getString("password").equals(txtPasswordLogin.getText())){
                            email=txtEmailLogin.getText();
                            initiateClient();
                            LoadingFrame obj = new LoadingFrame();
                            obj.setVisible(true);
                            dispose();
                        }
                        else{
                            lblNotification.setForeground(Color.red);
                            lblNotification.setText("Please check the password");
                        }
                    }
                    else{
                        lblNotificationLogin.setForeground(Color.red);
                        lblNotification.setText("User does not exists");
                    }
                }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Some issue"+e);
        }
    }//GEN-LAST:event_btnGoLoginActionPerformed

    private void btnSuggestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuggestionsActionPerformed
       FeedbackForm f1 = new FeedbackForm();
        f1.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSuggestionsActionPerformed

    private void btnBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackButtonActionPerformed
        if(page==1){
            System.out.println(page);
            pnlMainPanel1.setVisible(true);
            pnlSignUpAndLogin.setVisible(false);
            clearFields();
        }
        else if(page==2){
            System.out.println(page);
            pnlSignUpData.setVisible(true);
            pnlLoginPanel.setVisible(false);
            page=1;
            clearFields();
        }
    }//GEN-LAST:event_btnBackButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
         txtEmail.setForeground(f3f7f8);
        lblNotification.setForeground(f3f7f8);
        lblNotification.setText("Email should be in format:'someone@address.com'");
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if(txtEmail.getText().equals("")){
            lblNotification.setText("Please enter the email first");
            lblNotification.setForeground(Color.red);
            jspEmail.setBackground(Color.red);
            jspEmail.setForeground(Color.red);
            txtEmail.setForeground(Color.red);
        }
        else{
             jspEmail.setBackground(f3f7f8);
            jspEmail.setForeground(f3f7f8);
            txtEmail.setForeground(f3f7f8);
            lblNotification.setText("");
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtConfirmEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmEmailFocusGained
         txtConfirmEmail.setForeground(f3f7f8);
        if(txtEmail.getText().equals("")){
            lblNotification.setText("Please enter the email first");
            lblNotification.setForeground(Color.red);
            jspEmail.setBackground(Color.red);
            jspEmail.setForeground(Color.red);
            txtEmail.setForeground(Color.red);
        }
        else{
            lblNotification.setText("Re-enter the email");
        }
    }//GEN-LAST:event_txtConfirmEmailFocusGained

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        lblNotification.setForeground(f3f7f8);
        lblNotification.setText("Password should be 8 characters long");
        txtPassword.setForeground(f3f7f8);
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtConfirmEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmEmailFocusLost
        if(txtEmail.getText().equals("") || txtConfirmEmail.getText().equals("")){
            lblNotification.setText("Please enter the email");
            lblNotification.setForeground(Color.red);
            jspEmail.setBackground(Color.red);
            jspEmail.setForeground(Color.red);
            txtEmail.setForeground(Color.red);
            jspConfirmEmail.setBackground(Color.red);
            jspConfirmEmail.setForeground(Color.red);
            txtConfirmEmail.setForeground(Color.red);
        }
        else{
             jspEmail.setBackground(f3f7f8);
            jspEmail.setForeground(f3f7f8);
            jspConfirmEmail.setBackground(f3f7f8);
            jspConfirmEmail.setForeground(f3f7f8);
            lblNotification.setText("");
        }
        validateEmail();
    }//GEN-LAST:event_txtConfirmEmailFocusLost

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
         jspPassword.setForeground(f3f7f8);
         jspPassword.setBackground(f3f7f8);
          txtPassword.setForeground(f3f7f8);
          lblNotification.setText("Password sould be 8 characters long");
    }//GEN-LAST:event_txtPasswordFocusLost

    private void txtConfirmPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmPasswordFocusGained
         txtConfirmPassword.setForeground(f3f7f8);
        lblNotification.setForeground(f3f7f8);
        lblNotification.setText("Re-enter the password");
    }//GEN-LAST:event_txtConfirmPasswordFocusGained

    private void txtConfirmPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmPasswordFocusLost
        checkPassword();
    }//GEN-LAST:event_txtConfirmPasswordFocusLost

    private void lblEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmailMouseClicked
        txtEmail.requestFocus(true);
    }//GEN-LAST:event_lblEmailMouseClicked

    private void lblConfirmEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfirmEmailMouseClicked
         txtConfirmEmail.requestFocus(true);
    }//GEN-LAST:event_lblConfirmEmailMouseClicked

    private void lblPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPasswordMouseClicked
         txtPassword.requestFocus(true);
    }//GEN-LAST:event_lblPasswordMouseClicked

    private void lblConfirmPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfirmPasswordMouseClicked
         txtConfirmPassword.requestFocus(true);
    }//GEN-LAST:event_lblConfirmPasswordMouseClicked

    private void txtPasswordLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordLoginActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        pnlMainPanel1.setVisible(false);
        pnlSignUpAndLogin.setVisible(true);
        pnlSignUpData.setVisible(true);
        page=1;
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeedbackActionPerformed
        FeedbackForm f1 = new FeedbackForm();
        f1.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnFeedbackActionPerformed

    private void btnOurCoordinatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOurCoordinatesActionPerformed
        LocationFrame obj = new LocationFrame();
        startingPage.dispose();
        obj.setVisible(true);
    }//GEN-LAST:event_btnOurCoordinatesActionPerformed

    private void btnWhatWeServeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWhatWeServeActionPerformed
        // TODO add your handling code here:
        new ImagesPanel().setVisible(true);
    }//GEN-LAST:event_btnWhatWeServeActionPerformed
 
    //Methods for validations of data
    /*
    By:Harsh Kukreja
    The below method does the job of checking whether all the fields on Sign Up page are filled or not.
    */
    private boolean checkData(){
        if((txtEmail.getText().equals("")) || (txtConfirmEmail.getText().equals("")) || (txtPassword.getText().equals("")) || (txtConfirmPassword.getText().equals(""))){
           return false;
        }else{
            return true;
        }
    }
    /*
    By:Harsh Kukreja
    The below mehtod checks if the all the terms and conditions are accepted by the user.
    */
    private boolean checkCheckbox(){
         boolean jcbStatus = false;
        if(jcbTermsAndConditions.isSelected()){
            jcbTermsAndConditions.setForeground(f3f7f8);
            jcbStatus=true;
            return jcbStatus;
        }
        else{
            jcbTermsAndConditions.setForeground(Color.red);
            jcbStatus=false;
            return jcbStatus;
        }
    }
    /*
    By:Harsh Kukreja
    The below methods checks if the email is in correct format or not and also email is confirmed by user or not. 
    */
    private boolean validateEmail(){
            String emailPatternString = "^[_A-Za-z0-9\\+]+(\\.[_A-Za-z0-9-\\+]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
            Pattern emailPattern = Pattern.compile(emailPatternString);
            Matcher emailMatcher = emailPattern.matcher(txtEmail.getText());
            Matcher confirmEmailMatcher = emailPattern.matcher(txtConfirmEmail.getText());
            if(emailMatcher.matches() && confirmEmailMatcher.matches()){
                System.out.println("Inside first if");
                if(txtEmail.getText().equals(txtConfirmEmail.getText())){
                    System.out.println("Inside length");
                     return true;
                }
                else{
                    System.out.println("inside length else");
                    lblNotification.setForeground(Color.red);
                    lblNotification.setText("Emails does not match");
                    txtConfirmEmail.setForeground(Color.red);
                    txtEmail.setForeground(Color.red);
                    return false;
                }
            }
            else{
                System.out.println("inside first else");
                lblNotification.setForeground(Color.red);
                txtEmail.setForeground(Color.red);
                txtConfirmEmail.setForeground(Color.red);
                jspEmail.setBackground(Color.red);
                jspEmail.setForeground(Color.red);
                jspConfirmEmail.setBackground(Color.red);
                jspConfirmEmail.setForeground(Color.red);                
                lblNotification.setText("Please check the email");
               return false;
            }
    }
    /*
    By:Harsh Kukreja
    The below method clears all the fields once Registered Sucessfully.
    */
    private void clearFields(){
        txtEmail.setForeground(f3f7f8);
        txtConfirmEmail.setForeground(f3f7f8);
        txtPassword.setForeground(f3f7f8);
        txtConfirmPassword.setForeground(f3f7f8);
        txtEmail.setText("");
        txtConfirmEmail.setText("");
        txtPassword.setText("");
        txtConfirmPassword.setText("");
        txtEmailLogin.setText("");
        txtPasswordLogin.setText("");
        jspEmail.setForeground(f3f7f8);
        jspEmail.setBackground(f3f7f8);
        jspPassword.setForeground(f3f7f8);
        jspPassword.setBackground(f3f7f8);
        jspConfirmPassword.setForeground(f3f7f8);
        jspConfirmPassword.setBackground(f3f7f8);
        lblNotification.setForeground(f3f7f8);
        jcbTermsAndConditions.setSelected(false);
        lblNotification.setText("");
    }
    /*
    By:Harsh Kukreja
    The below method checks the password entered by the user.
    */
    private boolean checkPassword(){
        if(txtPassword.getText().equals(txtConfirmPassword.getText())){
            if(txtPassword.getText().length() < 8){
                lblNotification.setForeground(Color.red);
                lblNotification.setText("Password should be more than 8 characters");
                txtPassword.setForeground(Color.red);
                txtConfirmPassword.setForeground(Color.red);
                jspPassword.setForeground(Color.red);
                jspPassword.setBackground(Color.red);
                jspConfirmPassword.setForeground(Color.red);
                jspConfirmPassword.setBackground(Color.red);
                return false;
            }
            else{
                return true;
            }
        }
        else{
            lblNotification.setForeground(Color.red);
            lblNotification.setText("Passwords does not match");
            txtConfirmPassword.setForeground(Color.red);
            return false;
        }
    }
    /*
    By:Harsh Kukreja
    The below method checks whether the user is already registered or not.
    */
    private boolean checkUser(){
        
        boolean status=false;
        try {    
            String query="SELECT email FROM users";
            statement=connection.prepareStatement(query);
            rs=statement.executeQuery();
            System.out.println("The users are:");
            while(rs.next()){
                System.out.println(rs.getString("email"));
                if(rs.getString("email").equals(txtEmail.getText())){
                    System.out.println("equal");
                    lblNotification.setForeground(Color.red);
                    lblNotification.setText("User with this email already exists");
                    return false;
                }
                else{
                    return true;
                }
            }
            System.out.println("While me se true aaya");
            return true;
        } catch (Exception e) {
            lblNotification.setForeground(Color.red);
            lblNotification.setText("Some Issue");
            System.out.println("Catch me se false aaya");
            System.out.println(e);
            return false;
        }
    }
    /*Getters and Setters
    By:Harsh Kukreja
    */
    public static StartingPage getObject(){
        return new StartingPage();
    }
    public String getEmail(){
        return email;
    }
    public JPanel getMainPanel(boolean status){
        if(status){
            return pnlMainPanel;
        }
        else{
            return pnlMainPanel;
        }
    }
    
     public boolean initiateClient(){
        try {
            client = new Socket("127.0.0.1",8765);
            PrintWriter writer = new PrintWriter(client.getOutputStream(),true);
            writer.write("Hello");
            BufferedReader serverMessage = new BufferedReader(new InputStreamReader(client.getInputStream()));
//            int c=serverMessage.read();
//            StringBuffer s= new StringBuffer();
//            while((c!=-1)){
//                s.append((char)c);
//            }
            JOptionPane.showMessageDialog(null,"You are connected");
            return true;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"Issue in initiating Client"+ex);
            return false;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Macintosh*".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                startingPage.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlreadyUser;
    private javax.swing.JButton btnBackButton;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCanelLogin;
    private javax.swing.JButton btnFeedback;
    private javax.swing.JButton btnGo;
    private javax.swing.JButton btnGoLogin;
    private javax.swing.JButton btnImages;
    private javax.swing.JButton btnLocation;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnOrderNow;
    private javax.swing.JButton btnOurCoordinates;
    private javax.swing.JButton btnSuggestions;
    private javax.swing.JButton btnWhatWeServe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JCheckBox jcbTermsAndConditions;
    private javax.swing.JSeparator jspConfirmEmail;
    private javax.swing.JSeparator jspConfirmPassword;
    private javax.swing.JSeparator jspEmail;
    private javax.swing.JSeparator jspPassword;
    private javax.swing.JLabel lblConfirmEmail;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailLogin;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblImages;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblNotification;
    private javax.swing.JLabel lblNotificationLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordLogin;
    private javax.swing.JLabel lblVcm;
    private javax.swing.JLabel lblVcmLogo;
    private javax.swing.JLabel lblVesBackground;
    private javax.swing.JLabel lblVesLogo;
    private javax.swing.JLabel lblVivekanand;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblsignUp;
    private javax.swing.JPanel pnlLoginPanel;
    private javax.swing.JPanel pnlMainPanel;
    private javax.swing.JPanel pnlMainPanel1;
    private javax.swing.JPanel pnlRightSidePanel;
    private javax.swing.JPanel pnlSignUpAndLogin;
    private javax.swing.JPanel pnlSignUpData;
    private javax.swing.JPanel pnlToolbarsignUpAndLogin;
    private javax.swing.JTextField txtConfirmEmail;
    private javax.swing.JPasswordField txtConfirmPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmailLogin;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordLogin;
    // End of variables declaration//GEN-END:variables
    Connection connection=null;
    ResultSet rs=null;
    PreparedStatement statement=null;
    boolean flag=false;
    Color f3f7f8 = new Color(243,247,248);
    static String email="";
    static StartingPage startingPage = new StartingPage();
    int page=0; 
//    Timer t = new Timer(2000,new ActionListener(){
//        public void actionPerformed(ActionEvent ae){
//            t.stop();
//            pnlLoadingPanel.setVisible(false);
//        }
//    });
    Socket client;
}
