package projectui;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Harsh Kukreja
 */
public class SubmitDemo extends javax.swing.JFrame {

    /**
     * Creates new form SubmitDemo
     */
    Random random = new Random();
    Order1 obj = Order1.getObject();
    
    public SubmitDemo() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.decode("#1B1416"));
        this.setIconImage(new ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\letter-v.png").getImage());
        this.setSize(720,576);
        this.setForeground(Color.decode("#F3F7F8"));
        jdbConfirmation.setVisible(false);
        jdbConfirmation.setSize(631,300);
        retrieveFromDb();
        pnlPayment.setVisible(false);
        pnlLeftSide.setVisible(true);
        pnlRightSide.setVisible(true);
        lblConnectionLost.setVisible(false);
        btnGoBack.setVisible(false);
        btnExit.setVisible(false);
        btnLogout.setVisible(false);
        txtCardNo.setVisible(false);
        txtCvv.setVisible(false);
        lblErrorMessage.setVisible(false);
        lblCouponNumber.setText(""+random.nextInt(9999));
      //  finalList();  
        pack();
    }
    public void finalList(){
       String[] list = null;
       list=obj.getListOrdered();
        for (int i = 0; i < list.length; i++) {
            listFinal.add(list[i]);
        }
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdbConfirmation = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        pnlMainPanel = new javax.swing.JPanel();
        pnlLeftSide = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        lblUpperText = new javax.swing.JLabel();
        pnlRightSide = new javax.swing.JPanel();
        listFinal = new java.awt.List();
        lblOrder = new javax.swing.JLabel();
        lblCoupon = new javax.swing.JLabel();
        lblCouponNumber = new javax.swing.JLabel();
        btnPayLater = new javax.swing.JButton();
        btnPayNow = new javax.swing.JButton();
        lblCongo = new javax.swing.JLabel();
        lblEnjoyMeal = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        pnlPayment = new javax.swing.JPanel();
        pnlPaytm = new javax.swing.JPanel();
        btnPayByScan = new javax.swing.JButton();
        lblPaytmBlurImage = new javax.swing.JLabel();
        lblBarcode = new javax.swing.JLabel();
        lblPaytmLogo = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblScan = new javax.swing.JLabel();
        lblMobileNumber = new javax.swing.JLabel();
        lblNameImage = new javax.swing.JLabel();
        lblMobileNumberImage = new javax.swing.JLabel();
        lblNumber = new javax.swing.JLabel();
        lblTimeRemaining = new javax.swing.JLabel();
        lblTimer = new javax.swing.JLabel();
        btnGoBack = new javax.swing.JButton();
        pnlCreditCardPanel = new javax.swing.JPanel();
        btnPayByCard = new javax.swing.JButton();
        lblCreditCardBlurImage = new javax.swing.JLabel();
        lblCardNo = new javax.swing.JLabel();
        txtCardNo = new javax.swing.JTextField();
        lblMonth = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        jcbMonth = new javax.swing.JComboBox<>();
        jcbYear = new javax.swing.JComboBox<>();
        lblCvv = new javax.swing.JLabel();
        txtCvv = new javax.swing.JTextField();
        btnPayNowCreditCard = new javax.swing.JButton();
        jcbxSaveCard = new javax.swing.JCheckBox();
        lblMaestroUp = new javax.swing.JLabel();
        lblMaestroDown = new javax.swing.JLabel();
        lblCvvImage = new javax.swing.JLabel();
        lblVisa = new javax.swing.JLabel();
        lblMasterCard = new javax.swing.JLabel();
        lblPayPal = new javax.swing.JLabel();
        lblAmericanExpress = new javax.swing.JLabel();
        lblEncryption = new javax.swing.JLabel();
        lblErrorMessage = new javax.swing.JLabel();
        lblConnectionLost = new javax.swing.JLabel();
        pnlThanks = new javax.swing.JPanel();
        lblThanks = new javax.swing.JLabel();
        lblPossiblility = new javax.swing.JLabel();
        lblDash = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblVesLogo = new javax.swing.JLabel();

        jdbConfirmation.setModal(true);

        jPanel3.setBackground(new java.awt.Color(27, 20, 22));

        jLabel5.setFont(new java.awt.Font("Kalinga", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(243, 247, 248));
        jLabel5.setText("Thanks for using this application!");

        jLabel6.setFont(new java.awt.Font("Kalinga", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(243, 247, 248));
        jLabel6.setText("Please Rate us!");

        jButton3.setBackground(new java.awt.Color(27, 20, 22));
        jButton3.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(243, 247, 248));
        jButton3.setText("Yes,Sure");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 247, 248)));
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(27, 20, 22));
        jButton4.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(243, 247, 248));
        jButton4.setText("No,Thanks");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 247, 248)));
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jLabel6))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jdbConfirmationLayout = new javax.swing.GroupLayout(jdbConfirmation.getContentPane());
        jdbConfirmation.getContentPane().setLayout(jdbConfirmationLayout);
        jdbConfirmationLayout.setHorizontalGroup(
            jdbConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jdbConfirmationLayout.setVerticalGroup(
            jdbConfirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setType(java.awt.Window.Type.POPUP);

        pnlMainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLeftSide.setBackground(new java.awt.Color(255, 255, 255));

        lblImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\Other Images\\chris-fernandez-delivery_1x.jpg")); // NOI18N

        lblUpperText.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblUpperText.setForeground(new java.awt.Color(27, 20, 22));
        lblUpperText.setText("Here's Your Order");

        javax.swing.GroupLayout pnlLeftSideLayout = new javax.swing.GroupLayout(pnlLeftSide);
        pnlLeftSide.setLayout(pnlLeftSideLayout);
        pnlLeftSideLayout.setHorizontalGroup(
            pnlLeftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftSideLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblUpperText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        pnlLeftSideLayout.setVerticalGroup(
            pnlLeftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLeftSideLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(lblUpperText)
                .addGap(58, 58, 58)
                .addComponent(lblImage)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pnlMainPanel.add(pnlLeftSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 576));

        pnlRightSide.setBackground(new java.awt.Color(27, 20, 22));
        pnlRightSide.setForeground(new java.awt.Color(243, 247, 248));

        listFinal.setBackground(new java.awt.Color(27, 20, 22));
        listFinal.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        listFinal.setForeground(new java.awt.Color(243, 247, 248));

        lblOrder.setFont(new java.awt.Font("Kalinga", 1, 18)); // NOI18N
        lblOrder.setForeground(new java.awt.Color(243, 247, 248));
        lblOrder.setText("You Ordered: ");

        lblCoupon.setFont(new java.awt.Font("Kalinga", 1, 18)); // NOI18N
        lblCoupon.setForeground(new java.awt.Color(243, 247, 248));
        lblCoupon.setText("Your Coupon Number is : ");

        lblCouponNumber.setFont(new java.awt.Font("Kalinga", 1, 18)); // NOI18N
        lblCouponNumber.setForeground(new java.awt.Color(243, 247, 248));

        btnPayLater.setBackground(new java.awt.Color(27, 20, 22));
        btnPayLater.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        btnPayLater.setForeground(new java.awt.Color(243, 247, 248));
        btnPayLater.setText("Pay At Counter");
        btnPayLater.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 247, 248)));
        btnPayLater.setContentAreaFilled(false);
        btnPayLater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayLaterActionPerformed(evt);
            }
        });

        btnPayNow.setBackground(new java.awt.Color(27, 20, 22));
        btnPayNow.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        btnPayNow.setForeground(new java.awt.Color(243, 247, 248));
        btnPayNow.setText("Pay Now");
        btnPayNow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 247, 248)));
        btnPayNow.setContentAreaFilled(false);
        btnPayNow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayNowActionPerformed(evt);
            }
        });

        lblCongo.setFont(new java.awt.Font("Kalinga", 1, 18)); // NOI18N
        lblCongo.setForeground(new java.awt.Color(243, 247, 248));
        lblCongo.setText("Congratulations!");

        lblEnjoyMeal.setFont(new java.awt.Font("Kalinga", 1, 18)); // NOI18N
        lblEnjoyMeal.setForeground(new java.awt.Color(243, 247, 248));
        lblEnjoyMeal.setText("Enjoy Your Meal!");

        lblTotal.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(243, 247, 248));
        lblTotal.setText("Total(in Rs.)");

        lblTotalPrice.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        lblTotalPrice.setForeground(new java.awt.Color(243, 247, 248));

        btnCancel.setBackground(new java.awt.Color(27, 20, 22));
        btnCancel.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(243, 247, 248));
        btnCancel.setText("Exit");
        btnCancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 247, 248)));
        btnCancel.setContentAreaFilled(false);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRightSideLayout = new javax.swing.GroupLayout(pnlRightSide);
        pnlRightSide.setLayout(pnlRightSideLayout);
        pnlRightSideLayout.setHorizontalGroup(
            pnlRightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightSideLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(pnlRightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlRightSideLayout.createSequentialGroup()
                        .addComponent(lblCoupon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCouponNumber))
                    .addGroup(pnlRightSideLayout.createSequentialGroup()
                        .addGroup(pnlRightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTotal)
                            .addComponent(btnPayNow, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlRightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRightSideLayout.createSequentialGroup()
                                .addComponent(btnPayLater)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlRightSideLayout.createSequentialGroup()
                                .addComponent(lblTotalPrice)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRightSideLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlRightSideLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblOrder)))
                .addGap(113, 113, 113))
            .addGroup(pnlRightSideLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(pnlRightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRightSideLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblEnjoyMeal))
                    .addComponent(lblCongo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlRightSideLayout.setVerticalGroup(
            pnlRightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightSideLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblCongo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEnjoyMeal)
                .addGap(34, 34, 34)
                .addGroup(pnlRightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCoupon)
                    .addComponent(lblCouponNumber))
                .addGap(30, 30, 30)
                .addComponent(lblOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(pnlRightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotal)
                    .addComponent(lblTotalPrice))
                .addGap(18, 18, 18)
                .addGroup(pnlRightSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPayNow)
                    .addComponent(btnPayLater)
                    .addComponent(btnCancel))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pnlMainPanel.add(pnlRightSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 360, 580));

        pnlPayment.setBackground(new java.awt.Color(255, 255, 255));
        pnlPayment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPaytm.setBackground(new java.awt.Color(255, 255, 255));
        pnlPaytm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPayByScan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPayByScan.setText("Pay By Scan(Paytm)");
        btnPayByScan.setContentAreaFilled(false);
        btnPayByScan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayByScanActionPerformed(evt);
            }
        });
        pnlPaytm.add(btnPayByScan, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 0, 350, 580));

        lblPaytmBlurImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\Other Images\\paytmBlur.png")); // NOI18N
        pnlPaytm.add(lblPaytmBlurImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 580));

        lblBarcode.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\Other Images\\Barcode.png")); // NOI18N
        pnlPaytm.add(lblBarcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        lblPaytmLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\Other Images\\paytm.png")); // NOI18N
        pnlPaytm.add(lblPaytmLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 23, -1, 100));

        lblName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblName.setText("To pay VES CANTEEN");
        pnlPaytm.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 165, -1, 28));

        lblScan.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblScan.setForeground(new java.awt.Color(153, 153, 153));
        lblScan.setText("    Scan this Paytm code");
        pnlPaytm.add(lblScan, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 199, 155, -1));

        lblMobileNumber.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblMobileNumber.setForeground(new java.awt.Color(153, 153, 153));
        lblMobileNumber.setText("Or Enter Mobile Number:");
        pnlPaytm.add(lblMobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 472, 205, -1));

        lblNameImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\paytm(name).png")); // NOI18N
        pnlPaytm.add(lblNameImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 165, -1, -1));

        lblMobileNumberImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\paytm(mobile).png")); // NOI18N
        pnlPaytm.add(lblMobileNumberImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 501, -1, -1));

        lblNumber.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblNumber.setText("022-25227638");
        pnlPaytm.add(lblNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 501, -1, 44));

        lblTimeRemaining.setFont(new java.awt.Font("Kalinga", 1, 18)); // NOI18N
        lblTimeRemaining.setForeground(new java.awt.Color(31, 51, 104));
        lblTimeRemaining.setText("Time Remaining:");
        pnlPaytm.add(lblTimeRemaining, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 125, -1, -1));

        lblTimer.setFont(new java.awt.Font("Kalinga", 1, 18)); // NOI18N
        lblTimer.setForeground(new java.awt.Color(0, 189, 242));
        lblTimer.setText("60");
        pnlPaytm.add(lblTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 125, -1, -1));

        pnlPayment.add(pnlPaytm, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 0, 360, 580));

        btnGoBack.setBackground(new java.awt.Color(27, 20, 22));
        btnGoBack.setText("Go back");
        btnGoBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(27, 20, 22)));
        btnGoBack.setContentAreaFilled(false);
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });
        pnlPayment.add(btnGoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 540, 70, 30));

        pnlCreditCardPanel.setBackground(new java.awt.Color(255, 255, 255));
        pnlCreditCardPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPayByCard.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPayByCard.setText("Pay By Card");
        btnPayByCard.setContentAreaFilled(false);
        btnPayByCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayByCardActionPerformed(evt);
            }
        });
        pnlCreditCardPanel.add(btnPayByCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 360, 580));

        lblCreditCardBlurImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\Other Images\\creditcardblurrimage.png")); // NOI18N
        pnlCreditCardPanel.add(lblCreditCardBlurImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 580));

        lblCardNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCardNo.setText("Card No.");
        pnlCreditCardPanel.add(lblCardNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 48, -1, -1));

        txtCardNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCardNoActionPerformed(evt);
            }
        });
        pnlCreditCardPanel.add(txtCardNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 76, 294, 29));

        lblMonth.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMonth.setText("Month");
        pnlCreditCardPanel.add(lblMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 111, 63, -1));

        lblYear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblYear.setText("Year");
        pnlCreditCardPanel.add(lblYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 111, -1, -1));

        jcbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        pnlCreditCardPanel.add(jcbMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 139, 50, -1));

        jcbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050", "2051", "2052", "2053" }));
        pnlCreditCardPanel.add(jcbYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 139, -1, -1));

        lblCvv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCvv.setText("CVV");
        pnlCreditCardPanel.add(lblCvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 177, -1, -1));
        pnlCreditCardPanel.add(txtCvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 206, 50, 31));

        btnPayNowCreditCard.setBackground(new java.awt.Color(0, 189, 242));
        btnPayNowCreditCard.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPayNowCreditCard.setForeground(new java.awt.Color(255, 255, 255));
        btnPayNowCreditCard.setText("Pay Now");
        btnPayNowCreditCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayNowCreditCardActionPerformed(evt);
            }
        });
        pnlCreditCardPanel.add(btnPayNowCreditCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 346, 294, -1));

        jcbxSaveCard.setBackground(new java.awt.Color(255, 255, 255));
        jcbxSaveCard.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbxSaveCard.setText("Save this card for faster checkout");
        jcbxSaveCard.setBorder(null);
        jcbxSaveCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxSaveCardActionPerformed(evt);
            }
        });
        pnlCreditCardPanel.add(jcbxSaveCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 313, 294, -1));

        lblMaestroUp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMaestroUp.setForeground(new java.awt.Color(153, 153, 153));
        lblMaestroUp.setText("If your Maestro Card does not have Expiry Date");
        pnlCreditCardPanel.add(lblMaestroUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 255, -1, -1));

        lblMaestroDown.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMaestroDown.setForeground(new java.awt.Color(153, 153, 153));
        lblMaestroDown.setText("/CVV skip these fields");
        pnlCreditCardPanel.add(lblMaestroDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 278, 314, -1));
        pnlCreditCardPanel.add(lblCvvImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 205, -1, -1));

        lblVisa.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\visa (1).png")); // NOI18N
        pnlCreditCardPanel.add(lblVisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 457, -1, -1));

        lblMasterCard.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\mastercard (1).png")); // NOI18N
        pnlCreditCardPanel.add(lblMasterCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 457, -1, -1));

        lblPayPal.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\paypal (1).png")); // NOI18N
        pnlCreditCardPanel.add(lblPayPal, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 457, -1, -1));

        lblAmericanExpress.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\american-express (1).png")); // NOI18N
        lblAmericanExpress.setRequestFocusEnabled(false);
        pnlCreditCardPanel.add(lblAmericanExpress, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 457, -1, -1));

        lblEncryption.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblEncryption.setForeground(new java.awt.Color(153, 153, 153));
        lblEncryption.setText("Your Card details are secured via 128 Bit encryption");
        pnlCreditCardPanel.add(lblEncryption, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 389, -1, -1));

        pnlPayment.add(pnlCreditCardPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 580));

        lblErrorMessage.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\icons\\connection lost.png")); // NOI18N
        lblErrorMessage.setText("You Missed It.");
        pnlPayment.add(lblErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        pnlPayment.add(lblConnectionLost, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 440, 300));

        pnlMainPanel.add(pnlPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 580));

        pnlThanks.setBackground(new java.awt.Color(27, 20, 22));

        lblThanks.setFont(new java.awt.Font("Kalinga", 1, 36)); // NOI18N
        lblThanks.setForeground(new java.awt.Color(243, 247, 248));
        lblThanks.setText("Thanks for using our application!");

        lblPossiblility.setFont(new java.awt.Font("Kalinga", 1, 24)); // NOI18N
        lblPossiblility.setForeground(new java.awt.Color(243, 247, 248));
        lblPossiblility.setText("This was possible only under guidance of:");

        lblDash.setFont(new java.awt.Font("Kalinga", 0, 18)); // NOI18N
        lblDash.setForeground(new java.awt.Color(243, 247, 248));
        lblDash.setText("* Mr.Dasrath Kale");

        btnExit.setBackground(new java.awt.Color(27, 20, 22));
        btnExit.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(243, 247, 248));
        btnExit.setText("Exit");
        btnExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 247, 248)));
        btnExit.setContentAreaFilled(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(27, 20, 22));
        btnLogout.setFont(new java.awt.Font("Kalinga", 0, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(243, 247, 248));
        btnLogout.setText("Log Out");
        btnLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(243, 247, 248)));
        btnLogout.setContentAreaFilled(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblVesLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Harsh\\Documents\\NetBeansProjects\\ProjectUi\\Project images\\Other Images\\ves-logo.png")); // NOI18N

        javax.swing.GroupLayout pnlThanksLayout = new javax.swing.GroupLayout(pnlThanks);
        pnlThanks.setLayout(pnlThanksLayout);
        pnlThanksLayout.setHorizontalGroup(
            pnlThanksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThanksLayout.createSequentialGroup()
                .addGroup(pnlThanksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThanksLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(pnlThanksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPossiblility)
                            .addComponent(lblThanks)))
                    .addGroup(pnlThanksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlThanksLayout.createSequentialGroup()
                            .addGap(155, 155, 155)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlThanksLayout.createSequentialGroup()
                            .addGap(73, 73, 73)
                            .addComponent(lblDash)
                            .addGap(184, 184, 184)
                            .addComponent(lblVesLogo))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        pnlThanksLayout.setVerticalGroup(
            pnlThanksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThanksLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(lblThanks)
                .addGap(40, 40, 40)
                .addComponent(lblPossiblility)
                .addGroup(pnlThanksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThanksLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lblDash))
                    .addGroup(pnlThanksLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblVesLogo)))
                .addGap(31, 31, 31)
                .addGroup(pnlThanksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnLogout))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pnlMainPanel.add(pnlThanks, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPayNowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayNowActionPerformed
        // TODO add your handling code here:
        pnlLeftSide.setVisible(false);
        pnlRightSide.setVisible(false);
        lblConnectionLost.setVisible(false);
        pnlPayment.setVisible(true);
    }//GEN-LAST:event_btnPayNowActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        o.dispose();
        dispose();
        FeedbackForm obj = new FeedbackForm();
        obj.setVisible(true);
        jdbConfirmation.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
        o.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        pnlLeftSide.setVisible(true);
        pnlRightSide.setVisible(true);
        pnlPaytm.setVisible(false);
        lblConnectionLost.setVisible(false);
        btnPayNow.setEnabled(false);
        btnGoBack.setVisible(false);
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void btnPayLaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayLaterActionPerformed
        // TODO add your handling code here:
        pnlThanks.setVisible(true);
        pnlRightSide.setVisible(false);
        pnlLeftSide.setVisible(false);
        pnlPayment.setVisible(false);
        lblCreditCardBlurImage.setVisible(false);
        lblCreditCardBlurImage.setVisible(true);
        btnExit.setVisible(true);
        btnLogout.setVisible(true);
    }//GEN-LAST:event_btnPayLaterActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        StartingPage obj=StartingPage.getObject();
        obj.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtCardNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCardNoActionPerformed
    }//GEN-LAST:event_txtCardNoActionPerformed

    private void jcbxSaveCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxSaveCardActionPerformed
    }//GEN-LAST:event_jcbxSaveCardActionPerformed

    private void btnPayByCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayByCardActionPerformed
       lblCreditCardBlurImage.setVisible(false);
       btnPayByCard.setVisible(false);
       btnPayByScan.setVisible(true);
       lblPaytmBlurImage.setVisible(true);
       btnPayByScan.setEnabled(false);
       txtCardNo.setVisible(true);
       txtCvv.setVisible(true);
    }//GEN-LAST:event_btnPayByCardActionPerformed

    private void btnPayByScanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayByScanActionPerformed
       lblCreditCardBlurImage.setVisible(true);
       btnPayByCard.setVisible(true);
       btnPayByScan.setVisible(false);
       lblPaytmBlurImage.setVisible(false);
       btnPayByCard.setEnabled(false);
       jcbMonth.setVisible(false);
       jcbYear.setVisible(false);
       jcbxSaveCard.setVisible(false);
       btnPayNowCreditCard.setVisible(false);
       txtCardNo.setVisible(false);
       txtCvv.setVisible(false);
               
               
       t1.start();
    }//GEN-LAST:event_btnPayByScanActionPerformed

    private void btnPayNowCreditCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayNowCreditCardActionPerformed
        pnlThanks.setVisible(true);
        pnlPayment.setVisible(false);
        btnExit.setVisible(true);
        btnLogout.setVisible(true);
    }//GEN-LAST:event_btnPayNowCreditCardActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed
        
    //My Methods
   public static SubmitDemo getSubmitObject(){
       return new SubmitDemo();
   }
   
   /*
   By: Harsh Kukreja
   This method gets all the ordered item From the database and displays
   */
   public void retrieveFromDb(){
       int total=0;
       String sql="SELECT * from ordereditems WHERE email=? AND date=CURDATE()";
       Connection conn=MySqlConnect.connectDB();
       try {
           PreparedStatement statement = conn.prepareStatement(sql);
           statement.setString(1,obj.getEmail());
           ResultSet rs=statement.executeQuery();
               while(rs.next()){
                System.out.println(rs.getInt("totalprice"));
                total=total+rs.getInt("totalprice");
                listFinal.add(rs.getString("name"));
                System.out.println(total);
               }
           lblTotalPrice.setText(""+total);
       } catch (Exception e) {
           System.out.println("ERROR"+e);
       }
   }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Mcintosh*".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubmitDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubmitDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubmitDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubmitDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                o.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPayByCard;
    private javax.swing.JButton btnPayByScan;
    private javax.swing.JButton btnPayLater;
    private javax.swing.JButton btnPayNow;
    private javax.swing.JButton btnPayNowCreditCard;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> jcbMonth;
    private javax.swing.JComboBox<String> jcbYear;
    private javax.swing.JCheckBox jcbxSaveCard;
    private javax.swing.JDialog jdbConfirmation;
    private javax.swing.JLabel lblAmericanExpress;
    private javax.swing.JLabel lblBarcode;
    private javax.swing.JLabel lblCardNo;
    private javax.swing.JLabel lblCongo;
    private javax.swing.JLabel lblConnectionLost;
    private javax.swing.JLabel lblCoupon;
    private javax.swing.JLabel lblCouponNumber;
    private javax.swing.JLabel lblCreditCardBlurImage;
    private javax.swing.JLabel lblCvv;
    private javax.swing.JLabel lblCvvImage;
    private javax.swing.JLabel lblDash;
    private javax.swing.JLabel lblEncryption;
    private javax.swing.JLabel lblEnjoyMeal;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblMaestroDown;
    private javax.swing.JLabel lblMaestroUp;
    private javax.swing.JLabel lblMasterCard;
    private javax.swing.JLabel lblMobileNumber;
    private javax.swing.JLabel lblMobileNumberImage;
    private javax.swing.JLabel lblMonth;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNameImage;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblOrder;
    private javax.swing.JLabel lblPayPal;
    private javax.swing.JLabel lblPaytmBlurImage;
    private javax.swing.JLabel lblPaytmLogo;
    private javax.swing.JLabel lblPossiblility;
    private javax.swing.JLabel lblScan;
    private javax.swing.JLabel lblThanks;
    private javax.swing.JLabel lblTimeRemaining;
    private javax.swing.JLabel lblTimer;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JLabel lblUpperText;
    private javax.swing.JLabel lblVesLogo;
    private javax.swing.JLabel lblVisa;
    private javax.swing.JLabel lblYear;
    private java.awt.List listFinal;
    private javax.swing.JPanel pnlCreditCardPanel;
    private javax.swing.JPanel pnlLeftSide;
    private javax.swing.JPanel pnlMainPanel;
    private javax.swing.JPanel pnlPayment;
    private javax.swing.JPanel pnlPaytm;
    private javax.swing.JPanel pnlRightSide;
    private javax.swing.JPanel pnlThanks;
    private javax.swing.JTextField txtCardNo;
    private javax.swing.JTextField txtCvv;
    // End of variables declaration//GEN-END:variables

    static int i=60;
    static SubmitDemo o=new SubmitDemo();
    Timer t1 = new Timer(1000,new ActionListener(){
            //int i=60;
            public void actionPerformed(ActionEvent a){
                    i--;
                    setTimer();
            }
            public void setTimer(){
                lblTimer.setText(""+i);
                if(i==0){
                    lblConnectionLost.setVisible(true);
                    btnGoBack.setVisible(true);
                    lblErrorMessage.setVisible(true);
                    pnlPaytm.setVisible(false);
                    pnlCreditCardPanel.setVisible(false);
                    t1.stop();
                }
            }
        });
}
